### ISSUE TITLE
Float input seems to be converted to string

### ISSUE THREAD

**Issue by michaelriveraweb** [ncsa/DRYML#12]
[compute_prepare_type_conversion_bug.zip](https://github.com/ncsa/DRYML/files/11972048/compute_prepare_type_conversion_bug.zip)

System information:
Jupyter Notebook Running on HAL OnDeman HPC
OS Platform: Linux
DRYML version: 0.2.1
Python version: 3.9.12
CUDA Version: 11.7
GPU model and memory: Tesla V100-SXM2-16GB

I am building a Physics informed Neural network, and I am creating a physics model that is going to be implemented in the main neural network. This Physics model has two trainable parameters, alpha and beta. I am trying to make it so that the user could input a desire number value fir initializing alpha and beta, but this number seems to be converted to a string. I am wrapping the model with ModelWrapper.

**Comment by krafczyk** [comment]
@michaelriveraweb 

Can you copy the code into a code block like this:

```
test_code(val)
```

**Comment by michaelriveraweb** [comment]
Here is the code:

```
import torch
import torch.nn as nn
import dryml

class PhysModel(nn.Module):
    def __init__(self, alpha=None, beta=None):
        super(PhysModel, self).__init__()
        print("PhysModel.__init__ 1")
        print(alpha)
        print(type(alpha))
        if alpha is None:
            self.alpha = nn.Parameter(torch.rand(1))
        else:
            self.alpha = nn.Parameter(torch.tensor(alpha, dtype=torch.float32))
            
        if beta is None:
            self.beta = nn.Parameter(torch.rand(1))
        else:
            self.beta = nn.Parameter(torch.tensor(beta, dtype=torch.float32))
            
@dryml.context.compute_context(ctx_context_reqs={'torch': {}})
def test_func():
    from compute_prepare_type_conversion_bug import PhysModel
    from dryml import ObjectDef
    from dryml.models.torch.generic import ModelWrapper
    loss_phys_def = loss_phys_def = ObjectDef(
        ModelWrapper,
        PhysModel,
        alpha=10
    )
    loss_phys = loss_phys_def.build()
    loss_phys.compute_prepare()
    print(loss_phys.mdl)

if __name__ == "__main__":
    test_func()
```

**Comment by krafczyk** [comment]
Confirmed. Working on a fix.

**Comment by krafczyk** [comment]
Alright, I believe the issue is related to how the Wrappers and Object's special argument parsing semantics are interacting. the `alpha` variable is being sent as a plain argument not a keyword argument as is intended. I'm trying to write a new test case to expose this situation.

**Comment by krafczyk** [comment]
I discovered the issue, the object creation code was incorrect in ModelWrapper.
