### ISSUE TITLE
Type Error while training with a PyTorch Dataset

### ISSUE THREAD

**Issue by tejalkul** [ncsa/DRYML#9]
# Create function to generate the datasets
      def gen_dataset():
          # import some names
          import dryml
          import torchvision
          from dryml.data.torch import TorchDataset
          from dryml.data.tf import TFDataset
          from torchvision import transforms
      
          # Check that the context has torch ability, but don't get specific.
          dryml.context.context_check({'torch': {}})
          
          #Code to create Datasets
          to_tensor_transform =transforms.Compose([
                                 transforms.RandomHorizontalFlip(p=0.5),
                                 transforms.ToTensor(),
                                 transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]) # Normalize the Image        #ImageNet mean and std hence can be used for similar datasets)
                             ])
          
          train = torchvision.datasets.CIFAR10("home/tejalk00/REU/data/",train = True,download = True,transform=to_tensor_transform)       #Convert into tensors using transforms
          test = torchvision.datasets.CIFAR10("home/tejalk00/REU/data/",train = False,download = True,transform=to_tensor_transform)
          
          train_ds = TorchDataset(
              train,
              supervised=True,
          )
          
          test_ds = TorchDataset(
              test,
              supervised=True,
          )
          
          return train_ds, test_ds

   # Create function to train a model.
    # We use ctx_update_objs=True to indicate any objects we give the method should be updated with their
    # state at the end of the method.
    @dryml.compute_context(ctx_update_objs=True)
    def train_model(model):
        from temp_mod import gen_dataset
        train_ds, _ = gen_dataset()
        model.prep_train()
        
        model.train(train_ds)
    
    

# Create function to test model
      @dryml.compute
      def test_model(model):
          from dryml.metrics import categorical_accuracy
          from temp_mod import gen_dataset
          _, test_ds = gen_dataset()
      
          model.prep_eval()
          return categorical_accuracy(model, test_ds)

# Function to train multiple models
    def train_multiple(model_def=None, num_to_train=None, ctx_reqs=None):
        models = []
        accuracies = []
        for i in range(num_to_train):
            new_model = model_def.build()
            train_model(new_model, call_context_reqs=ctx_reqs)
            acc = test_model(new_model, call_context_reqs=ctx_reqs)
            accuracies.append(acc)
            models.append(new_model)
    
        return models, accuracies

# Model
    import dryml.models.torch
    import dryml.data.torch
    import torch
    
    dropout_p = 0.5
    classes = 10
    
    layer_defs=[
            [torch.nn.Conv2d, (3,64,3,1,0), {}],
            [torch.nn.ReLU, (), {}],
            [torch.nn.MaxPool2d, (3, 1), {}],
            [torch.nn.BatchNorm2d, (64,) ,{}],
            
            [torch.nn.Conv2d, (64,64,3,1,1),{}],
            [torch.nn.ReLU, (), {}],
            [torch.nn.MaxPool2d, (5,1), {}],
            [torch.nn.BatchNorm2d, (64,) ,{}],
            
            [torch.nn.Conv2d, (64,64,3,1,1),{}],
            [torch.nn.ReLU, (), {}],
            [torch.nn.MaxPool2d, (3,1), {}],
            [torch.nn.BatchNorm2d, (64,) ,{}],
            
            [torch.nn.Conv2d, (64,64,3,3,1),{}],
            [torch.nn.ReLU, (), {}],
            [torch.nn.MaxPool2d, (3,1), {}],
            [torch.nn.BatchNorm2d, (64,) ,{}],
            
            [torch.nn.AdaptiveAvgPool2d, (6,), {}],
        
            [torch.nn.Flatten, (), {}],
            
            [torch.nn.Dropout, (0.5,),{}],
            [torch.nn.Linear, (64*6*6,128), {}],
            [torch.nn.ReLU,(),{}],
            [torch.nn.Dropout,(0.5,), {}],
            [torch.nn.Linear,(128, 128), {}],
            [torch.nn.ReLU,(),{}],
            [torch.nn.Linear, (128, 10),{}],
            
            
        ] 
    
    
    
    mdl_def = ObjectDef(
       dryml.models.torch.generic.Sequential,
       layer_defs = layer_defs 
    )
    
    torch_mdl_def = ObjectDef(
        dryml.models.Pipe,
        ObjectDef(
            dryml.models.torch.generic.Trainable,
            model=mdl_def,
            train_fn=ObjectDef(
                dryml.models.torch.generic.BasicTraining,
                optimizer=ObjectDef(
                    dryml.models.torch.generic.TorchOptimizer,
                    torch.optim.Adam,
                    mdl_def,
                ),
                loss=ObjectDef(
                    dryml.models.torch.base.Wrapper,
                    torch.nn.CrossEntropyLoss
                ),
                epochs=15,
            )
        ),
        ObjectDef(
            dryml.data.torch.transforms.TorchDevice,
            device='cpu'
        ),
        best_cat_def,
    )

    torch_models,torch_accuracies = train_multiple(model_def = torch_mdl_def,num_to_train = num_to_train,ctx_reqs = {'tf': {} ,'torch':{'gpu/0': 1.} })

  # Error  

    Files already downloaded and verified
    Files already downloaded and verified
    Exception encountered in context thread! pid: 3975622
    Traceback (most recent call last):
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/context/process.py", line 34, in run
        super().run()
      File "/opt/miniconda3/envs/opence-v1.6.1/lib/python3.9/multiprocessing/process.py", line 108, in run
        self._target(*self._args, **self._kwargs)
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/context/process.py", line 186, in __call__
        self.final_call(f, ctx_send_q, ctx_ret_q, *args, **kwargs)
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/context/process.py", line 129, in final_call
        res = f(*args, **kwargs)
      File "/tmp/ipykernel_3969380/1338987022.py", line 10, in train_model
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/context/process.py", line 268, in wrapped_func
        res = f(*args, **kwargs)
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/models/pipe.py", line 37, in train
        step.train(
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/context/process.py", line 268, in wrapped_func
        res = f(*args, **kwargs)
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/models/torch/generic.py", line 135, in train
        self.train_fn(
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/context/process.py", line 268, in wrapped_func
        res = f(*args, **kwargs)
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/models/torch/generic.py", line 188, in __call__
        total_batches = data.count()
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/data/dataset.py", line 256, in count
        for e in self:
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/data/util.py", line 105, in nested_batcher
        flat_batch_data = list(map(
      File "/home/tejalk00/.local/lib/python3.9/site-packages/dryml/data/torch/dataset.py", line 111, in <lambda>
        lambda e: torch.stack(e, dim=0),
    TypeError: expected Tensor as element 0 in argument 0, but got int

# System Information:
    Jupyter Notebook Running on HAL OnDeman HPC
    OS Platform: Linux
    Python 3.9.12
    DRYML version: 0.2.1
    CUDA Version: 11.7
    GPU model and memory: Tesla V100-SXM2-16GB

**Comment by krafczyk** [comment]
@tejalkul , This error is happening because the 'Y' component of your dataset is yielding `int` values rather than tensors which is what the batcher expects. If you look at the second to last line of the stacktrace, you'll see nested_batcher is there, and it calls `torch.stack`. This function wants a list of tensors and not integer values. This is occuring at the torch vision dataset, and normally when dryml transforms one dataset into a `TorchDataset` a `tensor(x)` operation is applied to all values so this isn't a problem. However in this case, your vision dataset has plain integers for the 'Y' component.

The way around this is add a transformation to your `Pipe` to turn the integers in your 'Y' component into torch tensors. You could write a custom transformation for that, however I've felt for some time that my custom transformation support needs an upgrade. So I went and added that functionality to the `arbitrary-transformations` branch which I will soon merge.

Then if you change your pipe definition to this:
```
def to_tensor(x):
    import torch
    return torch.tensor(x)

torch_mdl_def = ObjectDef(
    dryml.models.Pipe,
    dryml.data.transforms.FuncTransform.from_function(
        to_tensor,
        mode='Y'
    ).definition().get_cat_def(),
    ObjectDef(
        dryml.models.torch.generic.Trainable,
        model=mdl_def,
        train_fn=ObjectDef(
            dryml.models.torch.generic.BasicTraining,
            optimizer=ObjectDef(
                dryml.models.torch.generic.TorchOptimizer,
                torch.optim.Adam,
                mdl_def,
            ),
            loss=ObjectDef(
                dryml.models.torch.base.Wrapper,
                torch.nn.CrossEntropyLoss
            ),
            epochs=15,
        )
    ),
    ObjectDef(
        dryml.data.torch.transforms.TorchDevice,
        device='cpu'
    ),
    ObjectDef(
        dryml.data.transforms.BestCat
    )
)
```

Then it works!
